#114 ツアーテンプレートの一覧を取得
e-harp-intern/R4FY pull request #269
Opened 2022-09-12 05:11 UTC by watashi-ha-utyujin

## 作業内容
- ツアーテンプレートの一覧を表示する機能を作成
- https://github.com/e-harp-intern/R4FY/wiki/templates-index
## 確認内容
- postmanで確認

2022-09-12 05:56 UTC, TomSuzuki requested changes

2022-09-12 05:56 UTC, TomSuzuki commented on api/app/controllers/api/v1/template_controller.rb
> +    templates = TourTemplate.find_by(id: params[:id])
変数名を `templates` から `template` にしておいてほしいです（取得できるのは単数なので）。

2022-09-13 00:49 UTC, watashi-ha-utyujin commented
修正しました

2022-09-13 01:27 UTC, TomSuzuki approved these changes
ok

2022-09-13 01:28 UTC, merged