#125 管理者側でガイドの参加可否情報を変更
e-harp-intern/R4FY pull request #270
Opened 2022-09-12 05:37 UTC by watashi-ha-utyujin

## 作業内容
- ガイドの参加可否情報を変更できるよう変更
- https://github.com/e-harp-intern/R4FY/wiki/tours-update
## 確認内容
- postmanで確認

2022-09-12 05:58 UTC, TomSuzuki requested changes

2022-09-12 05:58 UTC, TomSuzuki commented on api/app/controllers/api/v1/tours_controller.rb
> +    guide_schedules.update(possible: possible)
強制的に解答済み（`answered`を`true`）もお願いします。

2022-09-13 00:47 UTC, watashi-ha-utyujin commented
修正しました

2022-09-13 01:53 UTC, TomSuzuki approved these changes
多分OK

2022-09-13 01:54 UTC, merged