#74 中止メールを送信する
e-harp-intern/R4FY pull request #275
Opened 2022-09-12 07:47 UTC by watashi-ha-utyujin

## 作業内容
- ツアーを中止した際に、メールを送信するよう設定
## 確認内容
- postmanで動作を確認

2022-09-12 08:29 UTC, TomSuzuki requested changes

2022-09-12 08:29 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_controller.rb
> +      # tour_delete.update(tour_state_code: TOUR_STATE_CODE_CANCEL)
不要な行の削除をお願いします。

2022-09-12 08:29 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_controller.rb
> +    if tour_delete.tour_state_code == 2
`common.rb`で定数定義をしていますので、`2`を定数に置き換えお願いします。

2022-09-12 08:29 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_controller.rb
> +      guides = Guide.where(id: guides_id)
おそらく正しく取得できないように思います。

2022-09-13 00:39 UTC, watashi-ha-utyujin commented
修正しました

2022-09-13 01:53 UTC, TomSuzuki requested changes

2022-09-13 01:53 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_controller.rb
> +    if tour_delete.tour_state_code == TOUR_STATE_CODE_ASSIGNED
決定後なので、実績記入済みもあり得るかも？

2022-09-13 01:53 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_controller.rb
> +      guide_id = TourGuide.find_by(id: params[:id]).guide_id
担当ガイドは複数いる可能性もあります。

2022-09-13 01:53 UTC, TomSuzuki commented on api/app/mailers/tour_cancel_notify_mailer.rb
> +      subject: "【キャンセル通知】ツアーキャンセル通知",
「キャンセル」より「「中止」のほうがいいかも？

2022-09-13 04:47 UTC, watashi-ha-utyujin commented
修正しました

2022-09-13 05:06 UTC, TomSuzuki requested changes

2022-09-13 05:06 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_controller.rb
> +    # 担当者決定後の場合
インデントが崩れているような気がしますので修正をお願いします。以下のコマンドで一括修正できます（エラーが無い場合のみ）。

```shell
docker-compose run api rubocop -A
```

2022-09-13 06:27 UTC, TomSuzuki requested changes

2022-09-13 06:27 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_controller.rb
> +    if tour_delete.tour_state_code == TOUR_STATE_CODE_ASSIGNED || TourGuide.find_by(tour_id: params[:id]).achievements_entered == true
ここはツアーの状態を判別するところなので、`tour_delete.tour_state_code`と何かを比較するべきだと思います。

[Ruby 1個の変数に複数ある「or」をまとめて記述する | mebee](https://mebee.info/2021/04/05/post-32271/)

2022-09-13 06:27 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_controller.rb
> +        guides = Guide.find_by(id: tour_guides.guide_id)
細かいことですが、ここの変数名は単数形のほうがよいかと思います。

2022-09-14 01:56 UTC, watashi-ha-utyujin commented
修正しました

2022-09-14 01:57 UTC, TomSuzuki requested changes

2022-09-14 02:01 UTC, watashi-ha-utyujin commented
修正しました

2022-09-14 02:05 UTC, TomSuzuki approved these changes
OK

2022-09-14 02:05 UTC, merged