#129 管理者パスワードリセットメールの送信機能
e-harp-intern/R4FY pull request #280
Opened 2022-09-13 03:56 UTC by watashi-ha-utyujin

## 作業内容
- 管理者パスワードリセット用のメールを送信する機能を追加
- wiki ( https://github.com/e-harp-intern/R4FY/wiki/password_reset-create )
## 確認内容
- postmanとDB、Maildevで確認

2022-09-13 05:03 UTC, TomSuzuki requested changes

2022-09-13 05:03 UTC, TomSuzuki commented on api/app/controllers/concerns/common.rb
> +  URL_ADMIN_PASSWORD_RESET_TOKEN = "http://localhost:8080//rest/%<token>s".freeze
以下のように修正をお願いします（動作確認もお願いします）。
```ruby
URL_ADMIN_PASSWORD_RESET_TOKEN = "#{ENV['SERVER_PATH']}#{'/reset/%<token>s'.freeze}".freeze
```

2022-09-13 05:05 UTC, TomSuzuki requested changes

2022-09-13 05:05 UTC, TomSuzuki commented on api/app/views/password_reset_mailer/creation_email.text.erb
> +パスワードをリセット致しましたので、ご連絡いたします。
下記のURLからパスワードを再設定することができます。

2022-09-13 05:05 UTC, TomSuzuki commented on api/app/views/password_reset_mailer/creation_email.text.erb
> +入力期限まではこちらのリンクからパスワードの変更が可能です。
期限は無かったと思います。

2022-09-13 07:57 UTC, watashi-ha-utyujin commented
全部修正はしたのですが、URLだけ問題

2022-09-13 08:33 UTC, TomSuzuki requested changes

2022-09-13 08:33 UTC, TomSuzuki commented on api/app/views/password_reset_mailer/creation_email.text.erb
> +下記のリンクからログインと、パスワードの再設定をお願いいたします。
ログインはできないので、`下記のリンクからパスワードの再設定をお願いいたします。`だけでいい気がします。

2022-09-13 08:35 UTC, TomSuzuki requested changes

2022-09-13 08:35 UTC, TomSuzuki commented on api/app/controllers/api/v1/password_reset_controller.rb
> +    # 指定したIDのパスワードリセットトークンをすべて削除
論理削除済みの管理者アカウントが再発行できないように変更をお願いします。

2022-09-14 00:38 UTC, TomSuzuki approved these changes
OK

2022-09-14 00:38 UTC, merged