#271 中止済みのツアーの予定を入力不可に
e-harp-intern/R4FY pull request #335
Opened 2022-09-14 07:08 UTC by watashi-ha-utyujin

## 作業内容
- 中止されたツアーの予定を、ガイドが入力できないよう変更
## 確認内容
- DBで変更されないことを確認

2022-09-14 07:10 UTC, TomSuzuki requested changes
取得時も同様にエラーを返すように変更をお願いします。

2022-09-14 07:14 UTC, watashi-ha-utyujin commented
取得時に関してなのですが、パラメーターで獲得した直後に # ツアーが中止済みの場合 の機能を置くという感じでよろしいのでしょうか

2022-09-14 07:17 UTC, TomSuzuki commented
@watashi-ha-utyujin パラメータを使用してツアー情報を取得しないとできないかと思いますので、そのようにお願いします。
ここもガード節を使うときれいに書けるかと思います。

2022-09-14 07:20 UTC, watashi-ha-utyujin commented
位置変更しました

2022-09-14 07:21 UTC, TomSuzuki commented
@watashi-ha-utyujin あ、ここもでしたけど、取得時の機能修正もお願いします。

2022-09-14 07:55 UTC, watashi-ha-utyujin commented
取得側に機能を追加しました

2022-09-14 08:16 UTC, TomSuzuki requested changes
`index`側で存在しないトークンを指定するとサーバーエラーとなってしまいます。

トークンのチェックを先にしたほうがよいかと思います。

2022-09-15 00:07 UTC, watashi-ha-utyujin commented
修正しました

2022-09-15 00:18 UTC, TomSuzuki requested changes

2022-09-15 00:18 UTC, TomSuzuki commented on api/app/controllers/api/v1/guide_schedules_controller.rb
> +    response = {
ここの上にもコメントあると見やすいかも？

2022-09-15 00:18 UTC, TomSuzuki commented on api/app/controllers/api/v1/guide_schedules_controller.rb
> +    guide = Guide.find_by(id: token.guide_id)
ここにもコメントがあると嬉しい。

2022-09-15 00:24 UTC, TomSuzuki requested changes

2022-09-15 00:24 UTC, TomSuzuki commented on api/app/controllers/api/v1/guide_schedules_controller.rb
> +      possible: JSON.parse(guide_schedules.possible.to_json)
`JSON.parse(guide_schedules.possible.to_json)` → `guide_schedules` でいい気がします（他も）。

2022-09-15 00:43 UTC, watashi-ha-utyujin commented
パラメータ名とresponceとコメントを修正しました

2022-09-15 01:22 UTC, TomSuzuki approved these changes
OK

2022-09-15 01:22 UTC, merged