#195 ツアー作成後アカウント用ツアースケジュール入力機能
e-harp-intern/R4FY pull request #351
Opened 2022-09-15 06:58 UTC by watashi-ha-utyujin

## 作業内容
- ツアー作成後に作成されたアカウントにツアー予定入力メールを送信する機能です
- https://github.com/e-harp-intern/R4FY/wiki/tour_schedules-create
## 確認内容
- mailで動作確認

2022-09-15 07:36 UTC, TomSuzuki requested changes
ツアー作成時に予定入力メールを送信する場所でも、今回作った共通処理を使うように変更をお願いします。

2022-09-15 07:36 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_schedules_controller.rb
> +  include Common
これは継承もとで`include`しているはずなのでここには書かなくていいです。

2022-09-16 00:05 UTC, watashi-ha-utyujin commented
メソッド名をguide_schedule_mailerに変更しました

2022-09-16 00:23 UTC, TomSuzuki requested changes

2022-09-16 00:23 UTC, TomSuzuki commented on api/app/controllers/api/v1/tour_schedules_controller.rb
> +class Api::V1::TourSchedulesController < ApplicationController
`TourSchedulesMailerController` に変更だけお願いします。（名前がかぶっていました...）

2022-09-16 00:31 UTC, watashi-ha-utyujin commented
変更しました

2022-09-16 00:33 UTC, TomSuzuki approved these changes
OK？

2022-09-16 00:33 UTC, merged