[WIP] #374 ツアー詳細変更画面まで作成[機能はまだ]
e-harp-intern/R4FY pull request #417
Opened 2022-09-20 08:55 UTC by K-Todakun

2022-09-20 09:03 UTC, TomSuzuki requested changes

2022-09-20 09:03 UTC, TomSuzuki commented on web/src/i18n/languages/ja.js
> +            change: {
変更ではなく編集なので、「`edit`」へ変更をお願いします（ファイル名、パス等も）。
→ ほかの機能については後でやっておきます。

2022-09-20 09:03 UTC, TomSuzuki commented on web/src/router/index.js
> +    path: "/tours/:id/changetour",
`[`](path: "/tours/:id/edit",)`

2022-09-20 09:03 UTC, TomSuzuki commented on web/src/router/index.js
> +    component: () => import("@/views/tours/ChangeTourDetailView.vue"),
`"@/views/tours/TourEditView.vue"`

2022-09-20 09:10 UTC, TomSuzuki requested changes

2022-09-20 09:10 UTC, TomSuzuki commented on web/src/router/index.js
> +    component: () => import("@/views/tours/ChangeTourDetailView.vue"),
`EditTourView.vue`のほうがいいかも？

2022-09-21 00:36 UTC, K-Todakun commented
@TomSuzuki 
chnge→editに変更しました。
ファイル名の変更も行いました。
お時間がある際に、確認お願いいたします。

2022-09-21 01:15 UTC, TomSuzuki approved these changes
とりあえずマージ

2022-09-21 01:15 UTC, merged